EP-2194 - EP upgrade
CruGlobal/give-web pull request #1059
Opened 2023-10-05 19:22 UTC by wrandall22

[Jira](https://jira.cru.org/browse/EP-2194)

This PR merges all of the EP upgrade changes into master so we can go live with EP 8.1. All of this code was initially reviewed as it went into the `ep-upgrade` branch.

2023-10-05 19:22 UTC, wrandall22 commented
Not ready for go-live yet, but figured I'd get a PR out there.

2023-10-10 19:23 UTC, wrandall22 commented
Plan is to go live next Tuesday.

2023-10-12 13:33 UTC, dr-bizz requested changes

2023-10-12 13:33 UTC, dr-bizz commented on src/common/components/paymentMethods/creditCardForm/creditCardForm.component.js
We need to ensure that after merge with `master` we are using the new cruPayments.
```import * as cruPayments from '@cruglobal/cru-payments/dist/cru-payments'```

2023-10-12 13:33 UTC, dr-bizz commented on src/common/components/paymentMethods/bankAccountForm/bankAccountForm.component.js
Again with this page, we must ensure the new cruPayments is used after merge with `maaster`

2023-10-12 13:33 UTC, dr-bizz commented on src/app/analytics/analytics.factory.js
We'll need to merge this file carefully too.

2023-10-12 13:33 UTC, dr-bizz commented on .github/workflows/build.yml
Do we still need these extra branches in GHA?

2023-10-12 13:37 UTC, wrandall22 commented on src/common/services/paymentHelpers/extractPaymentAttributes.js
> +function flattenObject (obj) {
It is called in order service, profile service, and payment-methods component.

2023-10-12 13:43 UTC, wrandall22 commented on .github/workflows/build.yml
After we go live we won't need them, but I don't want to remove them until we do, so we can test changes quickly if needed. The current workflow is to put `ep-upgrade` into the stage/prod branches for deployment to their environments. It is unlikely we'll need to make front-end changes at this point, but if we do I'd have to put them back.

2023-10-12 13:45 UTC, wrandall22 commented on src/common/components/paymentMethods/creditCardForm/creditCardForm.component.js
Yes, this is using the new version

2023-10-12 13:46 UTC, wrandall22 commented on src/common/components/paymentMethods/bankAccountForm/bankAccountForm.component.js
Yep, we are. I've been pulling all the changes in from master as they happen.

2023-10-12 13:48 UTC, wrandall22 commented on src/app/analytics/analytics.factory.js
This should have all of the changes from `master`. I did notice on line 156 we have `siteSubSection`, but it never seems to get a value.

2023-10-12 13:59 UTC, wrandall22 commented on src/app/analytics/analytics.factory.js
Looks like this variable was never initialized, unless, when it was a `var` it was set from elsewhere.

2023-10-12 14:45 UTC, wrandall22 commented on src/common/services/hateoasHelper.service.js
> +    return undefined
I think I'll leave this one as-is.

2023-10-24 19:02 UTC, merged